version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine


  worker:
    build: .
    command: celery -A tasks.celery_tasks worker --loglevel=info
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A tasks.celery_tasks beat --loglevel=info
    depends_on:
      - redis

volumes:
  postgres_data: